### ISSUE TITLE
v 0.0.3 release with xml support and content of ticket

### ISSUE THREAD

**Issue by fferraro87** [zekzekus/pywhmcs#1]
hi,
when you will release 0.0.3 with xml support?
and with this version how can i get content of ticket?
if i use getticket i haven't "message" field

thanks

**Comment by zekzekus** [comment]
sorry for late reply. i am not working on this for a loong time. i can only merge any pull requests. and at the end it is a really simple script. 

i won't be working on this. sorry for inconvenience.
